share: example: subnetwork: demonstration/test
- Note: FAILING test!

The network and setup:
======================

This demonstration mimics the wanted aloma/core usage of Petri-Nets:
The inner network processes a single block, using multiple module
calls (of different type), here just producing and processing:

```
                  |-> (block_L) -> [produce_L] -> (produced_L) -|
(block) -> (dup) <                                               > [process]
                  |-> (block_R) -> [produce_R] -> (produced_R) -|
```

The outer net is generating blocks and assigns them with memory
slots. Therefore it either generates new slots (as long as there is
memory) or re-uses slots returned from the inner net.

The memory management distributes the available memory such that each
slot fits two blocks (one for L and one for R):

```
slot 0        slot 1        slot 2
------ ------ ------ ------ ----- ------ ...
^      ^      ^      ^      ^     ^
block  block  block  block  block block
L 0    R 0    L 1    R 1    L 2   R 2
```

So a slot requires `2 * block_size` space. The offsets for blocks
`L x` and `R x` are `2 * block_size * x + 0 * block_size` and `2 *
block_size * x + 1 * block_size` respectively.

- The driver creates a topology with `produce` and `process`
workers. The `produce` workers are getting `block_size` memory to be
able to produce a single block. The `process` workers are getting `2 *
block_size` in order to process two blocks. The transitions `produce`
and `process` require the capabilities with the same name.

The failure:
============

```
fatal error: in "share_example_subnetwork": std::runtime_error: Job <JOB>: failed: error-message := <AGENT>: produce-<WORKER>: call to 'subnetwork::process' failed: not enough local memory allocated: <2 * BLOCK_SIZE> bytes required, only <BLOCK_SIZE> bytes allocated
```

The `produce` worker tries to execute the `process` task but has not
enough memory.

Note: When changing from `inline="false"` to `inline="true"`, then the
test also fails:

```
fatal error: in "share_example_subnetwork": std::runtime_error: Job <JOB>: failed: error-message := <AGENT>: process-<WORKER>: call to 'subnetwork::process' failed: blocks differ: 'Struct [id := 12UL, slot := 10UL]' != 'Struct [id := 2UL, slot := 2UL]'
```

The `process` selects pairs of buffer that do not match their `id`.

How to fix it:
==============

- Option 1: Make sure all workers can execute all tasks. For example this diff
```
--- a/share/example/subnetwork/driver.cpp
+++ b/share/example/subnetwork/driver.cpp
@@ -112,7 +112,7 @@ BOOST_AUTO_TEST_CASE (share_example_subnetwork)
     ( vm
     , installation
     , str ( boost::format ("produce:2,%1% process:1,%2%")
-          % (1 * block_size)
+          % (2 * block_size)
           % (2 * block_size)
           )
     , rifds.entry_points()
```
provides enough space in all workers. This approach renders
capabilities useless.

- Option 2: Do not use sub networks and add conditions. This is the
current aloma/core approach. The corresponding diff is
```
--- a/share/example/subnetwork/process_all_blocks.xpnet
+++ b/share/example/subnetwork/process_all_blocks.xpnet
@@ -69,7 +69,7 @@
       <connect-out port="block" place="block_ready"/>
     </transition>

-    <transition name="process_single_block" inline="false">
+    <transition name="process_single_block" inline="true">
       <include-function href="process_single_block.xpnet"/>
       <connect-read port="memory" place="memory"/>
       <connect-read port="block_size" place="block_size"/>
--- a/share/example/subnetwork/process_single_block.xpnet
+++ b/share/example/subnetwork/process_single_block.xpnet
@@ -158,6 +158,9 @@
           </code>
         </module>
       </defun>
+      <condition>
+        ${block_L.id} :eq: ${block_R.id}
+      </condition>
       <connect-read port="memory" place="memory"/>
       <connect-read port="block_size" place="block_size"/>
       <connect-read port="tag_L" place="tag_L"/>
```

- Option 3: Proper support would not send the sub network to the
worker and passes the test without any further change.